config/routes.rb
Rails.application.routes.draw do
  resources :diaries
  resources :users

  get     'login',   to: 'sessions#new'
  post    'login',   to: 'sessions#create'
  delete  'logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord 
  has_secure_password validations: true

  validates :mail, presence: true, uniqueness: true

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  before_action :require_sign_in!
  helper_method :signed_in?

  protect_from_forgery with: :exception

  # remember_token(Cookie)をベースにcurrent_userオブジェクトをセットする
  def current_user
    puts "#{Time.now} ************current_user********************"
    remember_token = User.encrypt(cookies[:user_remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  #　サインイン処理を実施
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:user_remember_token] = remember_token
    user.update!(remember_token: User.encrypt(remember_token))
    @current_user = user
  end

  def sign_out
    @current_user = nil
    cookies.delete(:user_remember_token)
  end

  # サインイン済みか確認する
  def signed_in?
    @current_user.present?
  end

  private

    def require_sign_in!
      redirect_to login_path unless signed_in?
    end

end

app/controllers/concerns/logging_action.rb
class LoggingAction

  # around_action時に呼び出される(before,after両方)
  def around(controller)
    controller.logger.debug "#{Time.now} before: #{controller.action_name}"
    yield
    controller.logger.debug "#{Time.now} after: #{controller.action_name}"
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController

  before_action :set_diary, only: [:show, :edit, :update, :destroy]
  before_action :set_time, only: [:show, :index, :edit]
  around_action LoggingAction.new, only: [:index, :show, :index, :edit]

  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.all.order(:title)
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(diary_params)
    @diary[:author] = @current_user.name

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: '日記の作成が完了しました。' }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: '日記の更新が完了しました。' }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url, notice: '日記の削除が完了しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    def set_time
      @now = Time.now
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diary_params
      params.require(:diary).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # before_action :require_sign_in!, only: [:destroy]
  before_action :set_user, only: [:create]
  around_action LoggingAction.new, only: [:new, :create]
  # ログインなしでアクセス可能な画面を定義 
  skip_before_action :require_sign_in!, only: [:new, :create]
  
  def new
  end

  def create

    # autenticateはモデルでhas_secure_passwordを宣言していると自動的に使用できるようになる
    if @user.authenticate(session_params[:password])
      sign_in(@user)
      redirect_to diaries_path
    else
      # flash.now[:danger] = t('.flash.invalid_password')
      flash.now[:danger] = "パスワード違うで。[#{session_params[:mail]}]"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to login_path
  end

  private

    def set_user
      @user = User.find_by!(mail: session_params[:mail])
    rescue
      # flash.now[:danger] = t('.flash.invalid_mail')
      flash.now[:danger] = "そんなゆーざおらんで。[#{session_params[:mail]}]"
      render action: 'new'
    end

    # 許可するパラメータ
    def session_params
      params.permit(:mail, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  around_action LoggingAction.new, only: [:new, :create]
  # ログインなしでアクセス可能な画面を定義(ユーザ作成画面表示と作成処理) 
  skip_before_action :require_sign_in!, only: [:new, :create]
    
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # xxx_path => GET /xxx を生成 
      redirect_to login_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :mail, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/_form.html.erb
<%= form_with(model: diary, local: true) do |form| %>
  <% if diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
      <% diary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'タイトル' %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label '本文' %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit "#{button}", class: "submit-btn" %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<h1>日記更新</h1>

<%= render 'form', diary: @diary, button: '更新' %>

<%= link_to '詳細', @diary %> |
<%= link_to '戻る', diaries_path %>

app/views/diaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>日記一覧</h1>

<table class='bordered zebra'>
  <thead>
    <tr>
      <th>ID</th>
      <th>作成者</th>
      <th>タイトル</th>
      <th>登録日時</th>
      <th>更新日時</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @diaries.each do |diary| %>
      <tr>
        <td><%= diary.id %></td>
        <td><%= diary.author %></td>
        <td><%= link_to diary.title, diary %></td>
        <td><%= diary.created_at %></td>
        <td><%= diary.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '日記を新規作成', new_diary_path %>

app/views/diaries/new.html.erb
<h1>日記作成</h1>

<%= render 'form', diary: @diary, button: '登録' %>

<%= link_to '戻る', diaries_path %>

app/views/diaries/show.html.erb
<h1>日記詳細</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>現在時刻:</strong>
  <%= @now %>
</p>

<p>
  <strong>ID:</strong>
  <%= @diary.id %>
</p>

<p>
  <strong>作成者:</strong>
  <%= @diary.author %>
</p>

<p>
  <strong>タイトル:</strong>
  <%= @diary.title %>
</p>

<p>
  <strong>本文:</strong>
  <%= @diary.body %>
</p>

<p>
  <strong>登録日時:</strong>
  <%= @diary.created_at %>
</p>

<p>
  <strong>更新日時:</strong>
  <%= @diary.updated_at %>
</p>


<%= link_to '編集', edit_diary_path(@diary) %> |
<%= link_to '削除', @diary, method: :delete, data: {confirm: "#{@diary.title}を削除します。よろしいですか？"} %> |
<%= link_to '戻る', diaries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeeklyReports</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user.present? %>
      <div id="user-info">
        <%= @current_user.name %> さん
        <%= link_to  "sign_out", logout_path, method: :delete %>
      </div>
    <% else %>
      <%= link_to  "sign_in", login_path %>      
      <%= link_to  "sign_up", new_user_path %>      
    <% end %>
    <div id='contents'>
      <%= yield %>
    </div>

    <footer id='hige'>
      &copy; copyright 2018 Hogehoge CO.LTD
    </footer>
  </body>

</html>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true) do |form| %>

  <div class="field">
    <%= form.label '名前' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label 'メール' %>
    <%= form.text_area :mail %>
  </div>

  <div class="field">
    <%= form.label 'パスワード' %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label 'パスワード(確認)' %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit "登録", class: "submit-btn" %>
  </div>

<% end %>